# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c45b2025cf95e633a92905dc1cae666a0a75a55e6122204d610fbfb3ca1d5c667b06ffff5ffd118a9b84ece597717e3079b2d861be11ac3b398f815e7ac7c0e

test:
  secret_key_base: 06a948d77f3add0db86ef96f0ceb03fd701938ab23d8f913714f12fb53d8f4dbd3cb4af04f3d15a6f2df77101d57084dce617f9a15109538517a274235d67f61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
